# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-12 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190112_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='./static/images/'),
        ),
    ]
