# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-12 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190112_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='blog/static/images/'),
        ),
    ]
