# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-12 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190112_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='SerpentesBlog/blog/static/images/'),
        ),
    ]
